#!/usr/bin/env ruby
require 'sqlite3'


require_relative 'lib/environment.rb'
require_relative 'lib/parse_argv.rb'


command = ARGV[0]
options = ParseArgv.parse
errors = ParseArgv.validate options

if errors.empty?

  environment = Environment.type options[:environment] || "production"
  database = Environment.database_connection
  database.execute("insert into items ('name', 'targetInventory') values ('#{options[:name]}', #{options[:inv]})")
  puts "Looks like you successfully added something"
  # database.execute("insert into items ('name', 'targetInventory') values ('Target',                          10)")

else
  puts errors unless errors.empty?
end