#!/usr/bin/env ruby
require 'sqlite3'
require_relative './lib/helper.rb'
require_relative './models/staple.rb'
require_relative './models/purchase.rb'


require_relative 'lib/environment.rb'
require_relative 'lib/argument_parser.rb'


command = ARGV[0]
options = ArgumentParser.parse
options[:command] = command
errors = ArgumentParser.validate options unless command == "print"

if errors.empty?

  environment = Environment.type options[:environment] || "production"
  database = Environment.database_connection

  case command
  when "add"
    add_staple(options, database)
  when "purchase"
    add_purchase(options, database)
  when "set"
    set_inventory(options, database)
  when "print"
    print_grocery_list(options, database)
  else puts "command not found"
  end  

else
  puts errors unless errors.empty?
end

